language: node_js
node_js:
- '8'
env:
  global:
  - secure: Ws0qV5KaALv3mDVV9alnLwDIqv5P/r/+4Bugstfe312q/TZDHVeE9xy96vrc5B3JXLgbDdR3mbHuDiRTq9yR1sVe9pIXuGVHuGw5aggGSyAosi/+A6rdAoXbSPwU0gSe5fL9X0X8o+pvOR7TGdjTPvpHXUbZC15lVRafryuAOhjfh9DDSWdbA57GDDRAHwtCsX4eLDlkER9aTqf2lmG8nALw8VlES7UA9Rrxopas1DtqRZUlwmk2qa/cczRu3aKghBonpVjq/JaWJMXH9SS74TkGb10+iKq1oWs+fGQMb95iyFuO28mo58G28SqlsYRGA/Ea6v1LayJ3rUJBweYGGwNpcZMj02iIrbJ7fSbjPJue7PVqfmTFzNNaznRxuHAjaAw17KW8A4o0whjnrJgwFQvMTXRhTu0UetHWJFEYVdswTdfbiWKnVhjJGz1yWXGiH2qji5LVuAT2clZZNWv7aXtdOpM0KGmiLuV5ROUflzLqHNrffHnAZUtbIMIqoyo0pzBthGtx0xcRW9RQBOEVk/Lzjg3fHOJFdhHQyypfvRAt4ksXxwkx390ORZVXnckiZ3TImibZe3uhTfphwPx2560Z8LeOD5aSPjCHej36Hl7Qj4o/9MM9eaQ8Fy5CtGnsFuwFZN8DrYfHfQcp4zJgt051T1DEnPe1aRm8dpDmBO0=
  - secure: AN9dOfeDcfg8fh74Bzj+jUDFnma/HDdSPzGCe6P67Iz7FQSBJgDHJnnJ1Jp+kJUP2Cmt+jxasXkfAhRl6Xqy4cUZw1gMImpAo0UzMsld57fqXKm+Xe0LvIgwRRTngGqfds4a8gxuVBaYeeQS/bzEKfBdDgTNx39bALn8q08SSXrv2w4ewonO0wpCSgaHYFjGiObXtXyXZ3De4kcCuhK+tK2RP1jWfjUPVRxXStHR5lSrvNt2Et2xN9nqIW2pTd2TXYGHzH/Zyxvy8ap1djpUoS1VNjO8gDfoJXLE3RqehJPbVFt8l8Mv/62Z+AxtW8VZ20NQzDoc44fjiKcySKWWJaZ6FREIaGtaHX/WyJnLM7vSRO8LSTd0ERTUN685ISq4oIfRC6+siN3iCaxJ6BvF4ApIr23SqpZch+7AhqmhWypFGL1IjxhypUXWu/lHhbY56KsWxL5sHLKE0ugiDYy6tUNCcm2k5qkWP2HCfKMZYjGlLVxV3pI+Kesb6yHA29ygdTMEp9F+AlJEA1s/yCX2vkn6BDoYrpeEArtwwVBt0y6hsCBhODURyDleuIjpXI2QTzz6yL9WGEErl4o02Hgs8s1Mx8FwbNoTWgeXjYoPbZyoqxt/IWL8XV7tqK9p7PU+ZNgB4V7fKqFPhbkSh9lkrEY3VWNfzbWrrcJMhK5BGZA=
cache:
  directories:
  - node_modules
before_deploy: npm run semantic-release pre
after_deploy: npm run semantic-release post
deploy:
  skip_cleanup: true
  provider: script
  script: npm publish
  on:
    repo: musicociel/orchestrator
    branch: master
